// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH0G9ZksvHmGoXjNdJDJA40yZLazutYJo',
    appId: '1:311718291598:web:e595c92adedbf1384ac1df',
    messagingSenderId: '311718291598',
    projectId: 'regreenai',
    authDomain: 'regreenai.firebaseapp.com',
    storageBucket: 'regreenai.firebasestorage.app',
    measurementId: 'G-YG4MQV8F60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvSTvl8hGg3GsLq8oiHwpIBCohn3GCrg',
    appId: '1:311718291598:android:be00ec85dd404be24ac1df',
    messagingSenderId: '311718291598',
    projectId: 'regreenai',
    storageBucket: 'regreenai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwK2ONfRQPI7vdWRLiPwfYbKs7_cRt9L8',
    appId: '1:311718291598:ios:8f914222f882f9344ac1df',
    messagingSenderId: '311718291598',
    projectId: 'regreenai',
    storageBucket: 'regreenai.firebasestorage.app',
    iosBundleId: 'com.example.regreenai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwK2ONfRQPI7vdWRLiPwfYbKs7_cRt9L8',
    appId: '1:311718291598:ios:8f914222f882f9344ac1df',
    messagingSenderId: '311718291598',
    projectId: 'regreenai',
    storageBucket: 'regreenai.firebasestorage.app',
    iosBundleId: 'com.example.regreenai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH0G9ZksvHmGoXjNdJDJA40yZLazutYJo',
    appId: '1:311718291598:web:1caaf461da9415304ac1df',
    messagingSenderId: '311718291598',
    projectId: 'regreenai',
    authDomain: 'regreenai.firebaseapp.com',
    storageBucket: 'regreenai.firebasestorage.app',
    measurementId: 'G-TL3NGLWWEC',
  );
}
